### PR TITLE
fix: prevent timeout when getting studies

### LINKED ISSUE #501: StudyAccessUtil making services hard to test
Update: Has created StudyModelService(IStudyModelService), which ancapsulates the StudyQueries and StudyAccessUtil static utils. Currently only in use in one other service, but this should replace all usage of the static utils

**### Initial notes:**

StudyAccessUtil is used on many services to check if the user has access and filter study lists based on that.
Problem is that it is a static util and not injectable, causing pain when testing.

Should rethink the service architecture a bit. There is probably to much non-db-logic in the various services, we might need a Study service that only serves the db model

### LINKED ISSUE #635: Get study by id call sometmes times out
StudySingularQueries.GetStudyByIdCheckAccessOrThrow sometimes times out. I'ts referenced by 22 classes
It's a one sice fits all method, needs to go through every place it's used and think through the includes

### PR DESCRIPTION
**Pull request by krsteen**

### CODE REVIEW

**Comment by krsteen** [comment]
closes #635

**Comment by krsteen** [comment]
closes #501

File: src/Sepes.Infrastructure/Model/Automapper/AutoMappingConfigs.cs [hunk 1]
```diff
@@ -30,6 +31,8 @@ public AutoMappingConfigs()
 
 
             CreateMap<Study, StudyListItemDto>();
+            CreateMap<StudyListItemDto, StudyListItemResponse>()
+             .ForMember(dest => dest.Id, source => source.MapFrom(x => x.StudyId));
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Model/Automapper/AutoMappingConfigs.cs]: Would it be difficult to just have ID on both of these classes?

File: src/Sepes.Infrastructure/Service/Queries/StudyBaseQueries.cs [hunk 2]
```diff
@@ -23,18 +22,59 @@ public static IQueryable<Study> StudyDetailsQueryable(SepesDbContext db)
...
+                .Include(s => s.StudyDatasets)
+                    .ThenInclude(sds=> sds.Dataset);
+        }
+
+        public static IQueryable<Study> StudyDatasetCreationQueryable(SepesDbContext db)
+        {
+            return StudyDatasetsQueryable(db)
+                .Include(s => s.Resources)
+                .ThenInclude(r=> r.Operations);
         }
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/Queries/StudyBaseQueries.cs:78]: Would GraphQL be another way of doing this? If you have heard about it. Not suggestion we should change it, since it is another type of API. (GraphQL API)

File: src/Sepes.Infrastructure/Service/Study/StudyServiceBase.cs [hunk 3]
```diff
@@ -28,24 +29,37 @@ public StudyServiceBase(SepesDbContext db, IMapper mapper, ILogger logger, IUser
...
             await StudyPermissionsUtil.DecorateDto(_userService, studyFromDb, studyDetailsDto.Permissions);
+            var elapsedUrl2 = spElapsed.ElapsedMilliseconds;
+            spElapsed.Restart();
 
             foreach (var curDs in studyDetailsDto.Datasets)
             {
                 curDs.Sandboxes = curDs.Sandboxes.Where(sd => sd.StudyId == studyId).ToList();
             }
+            var elapsedFiltered = spElapsed.ElapsedMilliseconds;
+            spElapsed.Restart();
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/Study/StudyServiceBase.cs]: What are the purpose of these timers?

File: src/Sepes.Infrastructure/Service/UserService.cs [hunk 4]
```diff
@@ -62,10 +51,10 @@ public async Task<UserDto> GetUserByIdAsync(int userId)
             return userDto;
         }
 
-        async Task<User> EnsureDbUserExists(bool includeParticipantInfo = false)
+        async Task<User> EnsureDbUserExists()
         {
            var sp = Stopwatch.StartNew();
-            return await ThreadSafeUserCreatorUtil.EnsureDbUserExistsAsync(_db, _currentUserService, _azureUserService, includeParticipantInfo);
+            return await ThreadSafeUserCreatorUtil.EnsureDbUserExistsAsync(_db, _currentUserService, _azureUserService);
             var elapsed = sp.ElapsedMilliseconds;
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/UserService.cs:58]: This line will not run

**Review by HansKristianVikOlsen — APPROVED** [review]
See comments

File: src/Sepes.Infrastructure/Service/Study/StudyServiceBase.cs (hunk 3 above)
Comment (krsteen) [reply src/Sepes.Infrastructure/Service/Study/StudyServiceBase.cs]: Ah, those should not have made it out, removed it now

File: src/Sepes.Infrastructure/Model/Automapper/AutoMappingConfigs.cs (hunk 1 above)
Comment (krsteen) [reply src/Sepes.Infrastructure/Model/Automapper/AutoMappingConfigs.cs]: Just had to change one field of the query actually

File: src/Sepes.Infrastructure/Service/Queries/StudyBaseQueries.cs (hunk 2 above)
Comment (krsteen) [reply src/Sepes.Infrastructure/Service/Queries/StudyBaseQueries.cs:78]: Not exactly, that would be to add more flexibility to external customers of the api? But these queries are for internal usage by the program
