### PR TITLE
fix(dataset): getting server ip retries 3 times and caching result

### LINKED ISSUE #579: IpAddressUtil: Convert to a service and inject it. Mock it in test
IpAddressUtil is a static class. 
One ofthe methods calls a web service
Should be an injectable service insteasd

### LINKED ISSUE #584: dataset get public ip fails - add retry
When entering a dataset, the get public ip fails often. We should have a retry mechanizm

### PR DESCRIPTION
**Pull request by krsteen**
closes #584
closes #579

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/PublicIpService.cs [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+                                }
+                            }
+                            catch (Exception ex)
+                            {
+                                errorMessageSb.AppendLine(await GetPublicIpErrorMessage(curIpUrl, responseMessage: responseMessage, exception: ex));
+                            }
+                        }                      
+                    }
+                }
+
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/PublicIpService.cs]: Is it more correct to use a Do while loop? It will run minimum one time anyways. Does not matter really though

File: src/Sepes.Infrastructure/Service/PublicIpService.cs [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+                return _serverPublicIp;
+            }           
+            finally
+            {
+                _semaphore.Release();
+            }
+        }
+
+        async Task<string> GetServerPublicIpFromExternalService()
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/PublicIpService.cs]: Can this be tested?

**Review by HansKristianVikOlsen — APPROVED** [review]
5/7

**Review by HansKristianVikOlsen — APPROVED** [review]
