### PR TITLE
fix(study): remove logo if logoUrl is empty

### LINKED ISSUE #588: Study Logo: add endpoing for removing study logo

### PR DESCRIPTION
**Pull request by HansKristianVikOlsen**
Closes #588

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/Study/StudyUpdateService.cs [hunk 1]
```diff
@@ -54,6 +55,12 @@ public async Task<StudyDetailsDto> UpdateMetadataAsync(int studyId, StudyDto upd
                 studyFromDb.WbsCode = updatedStudy.WbsCode;
             }
 
+            if(updatedStudy.LogoUrl == "")
```
Comment (krsteen) [inline src/Sepes.Infrastructure/Service/Study/StudyUpdateService.cs]: Should use string.IsNullOrWhitespace(updatedStudy.LogoUrl)

**Review by krsteen — CHANGES_REQUESTED** [review]

**Review by krsteen — APPROVED** [review]
