### PR TITLE
fix(dataset): new sas token endpoing for deleting files

### LINKED ISSUE #590: Dataset: New endpoing for sas key for deleting files

### PR DESCRIPTION
**Pull request by HansKristianVikOlsen**
Closes #590

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/Azure/StorageAccount/AzureStorageAccountTokenService.cs [hunk 1]
```diff
@@ -48,6 +48,11 @@ public async Task<UriBuilder> CreateFileUploadUriBuilder(string containerName, C
             return await CreateUriBuilderWithSasToken(containerName, permission: BlobContainerSasPermissions.Write, expiresOnMinutes: 30, cancellationToken: cancellationToken);
         }
 
+        public async Task<UriBuilder> CreateFileDeleteUriBuilder(string containerName, CancellationToken cancellationToken = default)
+        {
+            return await CreateUriBuilderWithSasToken(containerName, permission: BlobContainerSasPermissions.Delete, expiresOnMinutes: 30, cancellationToken: cancellationToken);
```
Comment (krsteen) [inline src/Sepes.Infrastructure/Service/Azure/StorageAccount/AzureStorageAccountTokenService.cs]: I would set the expiresOnMinutes to 5 mins instead of 30, since it's a more "desctructive" action to delete files than to create them. Can you also rename it to expiresInMinutes? Probably a typo by me

**Review by krsteen — CHANGES_REQUESTED** [review]

File: src/Sepes.Infrastructure/Service/Azure/StorageAccount/AzureStorageAccountTokenService.cs (hunk 1 above)
Comment (HansKristianVikOlsen) [reply src/Sepes.Infrastructure/Service/Azure/StorageAccount/AzureStorageAccountTokenService.cs]: Oh yeah, forgot to change it

**Review by krsteen — APPROVED** [review]
