### PR TITLE
fix(sandbox): sort sizes by price with lowest cost first

### LINKED ISSUE #423: Sort Sizes after price
Add cost of sizes in db and sort them after price so frontend can display them in order of increasing price

### PR DESCRIPTION
**Pull request by HansKristianVikOlsen**
Closes #423

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineSizeService.cs [hunk 1]
```diff
@@ -101,6 +104,7 @@ public async Task UpdateVmSizeCache(CancellationToken cancellationToken = defaul
                     {
                         if (existingSizeItemsForRegion.TryGetValue(curAzureSku.Name, out curVmSizeInDb))
                         {
+                            curVmSizeInDb.Price = _azureCostManagementService.GetSizePrice(curVmSizeInDb.Key).Result;
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineSizeService.cs]: I am not quite sure where to put this.. it is in multiple places right now. Maybe you can give me a tip since you know the logic better?

File: src/Sepes.Infrastructure/Service/Azure/AzureCostManagementService.cs [hunk 2]
```diff
@@ -30,6 +30,22 @@ public async Task<double> GetVmPrice(string region, string size, CancellationTok
...
+
+            var relevantPriceItem = prices.Items.Where(p => p.effectiveStartDate <= DateTime.UtcNow).OrderByDescending(p => p.retailPrice).FirstOrDefault();
+
+            if (relevantPriceItem == null)
+            {
+                return 0.0;
+            }
+
+            return relevantPriceItem.retailPrice * 730; //Prices are per hour, azure defaults to 730 hours/month in their web interface
+        }
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/Azure/AzureCostManagementService.cs:49]: I made an extra function for get size. Are you okay with this? It is the same code except for not including region in the request, So can probably refactor them into one or something
