### PR TITLE
Fix/sandbox name validation

### LINKED ISSUE #526: Create sandbox: Not preventing duplicate Sandbox name, causing errors when creating resources
**Background:**
Creating two Sandboxes with the same name should not be allowed
Creating a Sandbox with the same name as a SOFT DELETED sandbox should be allowed

Have to add a check that supports both these scenarios. As of now it fails later in the process with a error message not as good.

### PR DESCRIPTION
**Pull request by krsteen**
Closes #526

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/Sandbox/SandboxService.cs [hunk 1]
```diff
@@ -150,6 +151,14 @@ public async Task<SandboxDetailsDto> CreateAsync(int studyId, SandboxCreateDto s
             }
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/Sandbox/SandboxService.cs:151]: Codeql does not like generic catch clauses, do you have any suggestions of an alternative?

**Review by HansKristianVikOlsen — APPROVED** [review]

**Comment by HansKristianVikOlsen** [comment]
See comment
