### PR TITLE
fix(vm): validate password and throw error if it does not meet requir…

### LINKED ISSUE #337: Vm Creation: Fails if user selects password that does not conform to requirements. Must add validation and perhaps a retry mechanizm
Create or select a study
Create or select a Sandbox
Create a VM with a password that does not conform to Azure Password Requirements 
VM Creation fails

### PR DESCRIPTION
**Pull request by HansKristianVikOlsen**
…ements

Closes #337

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineService.cs [hunk 1]
```diff
@@ -220,8 +226,41 @@ async Task<CloudResource> GetVmResourceEntry(int vmId, UserOperation operation)
...
+            {
+                errorString += "Missing one special character. ";
+            }
+            if (!limit.IsMatch(password))
+            {
+                errorString += "Outside the limit (12-123). ";
+
+            }
+            return errorString;
+            //return upper.IsMatch(password) && number.IsMatch(password) && special.IsMatch(password) && limit.IsMatch(password);
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineService.cs]: Alternative without error message

File: src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineService.cs [hunk 2]
```diff
@@ -73,6 +74,11 @@ public class VirtualMachineService : IVirtualMachineService
 
         public async Task<VmDto> CreateAsync(int sandboxId, CreateVmUserInputDto userInput)
         {
+            var anyValidationErrorsInPassword = ValidateVmPassword(userInput.Password);
+            if (!String.IsNullOrWhiteSpace(anyValidationErrorsInPassword))
+            {
+                throw new Exception($"{anyValidationErrorsInPassword}");
+            }
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/VirtualMachine/VirtualMachineService.cs]: Move into function

**Review by krsteen — APPROVED** [review]

**Review by krsteen — APPROVED** [review]
