### PR TITLE
fix(dataset): assign custom role for dataset resource group

### LINKED ISSUE #692: No access when trying to view files in custom dataset from the Azure portal
You do not have permissions to use the access key to list data. Click to learn more about authenticating with Azure Storage.
The client 'CTIM@equinor.com' with object id '383c38d7-cd1d-4cf0-b9a5-4fa70cf19101' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/6cfb8f33-6d4b-43bf-9000-91fd6f53ca28/resourceGroups/rg-study-christertest01-datasets-765/providers/Microsoft.Storage/storageAccounts/stdstestdatad69c4' or the scope is invalid. If access was recently granted, please refresh your credentials. 

User who creates the custom dataset will only get read access on the storage account. This is not enough to view, add or delete files

https://docs.microsoft.com/nb-no/azure/storage/blobs/authorize-data-operations-portal

### PR DESCRIPTION
**Pull request by krsteen**
Previously, the reader role was assigned for owners and sponsor rep, on the resource group containing the datasets. This role did not grant permission to create/read/delete blobs. A custom role has been created instead. This fix ensures that role assignment is set instead. The worker must have the id set in config, key is
Closes #692

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/DataModelService/CloudResource/CloudResourceReadService.cs [hunk 1]
```diff
@@ -64,16 +64,21 @@ public async Task<bool> ResourceIsDeleted(int resourceId)
             return SoftDeleteUtil.IsMarkedAsDeleted(resource);
         }
 
-        public async Task<List<int>> GetDatasetResourceGroupIdsForStudy(int studyId)
+        IQueryable<CloudResource> DatasetResourceGroupQueryable(int studyId)
         {
-            var resourceGroupsQueryable =
-             _db.CloudResources.Where(r => r.StudyId == studyId
+            return _db.CloudResources.Where(r => r.StudyId == studyId
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/DataModelService/CloudResource/CloudResourceReadService.cs:69]: The "r" is whatever one choose here, and it is an r for "resource" I presume. Just curious why we just write the one letter, would it be easier for an outside programmer to write "resource" or something else for the code? Could also be maybe "cr". I see that you also call it "r" on line 79 in this file, even though it means something different. But I guess it is okay since you have the context? What do you think?

File: src/Sepes.Provisioning/Service/RoleProvisioningService.cs [hunk 2]
```diff
@@ -104,22 +113,33 @@ async Task SetRoleAssignments(CloudResourceOperationDto operation, Study study,
...
+            else
+            {
+                throw new Exception($"Unable to determine role assignments, unknown purpose {operation.Resource.Purpose} for resource {operation.Resource.Id}");
+            }
             
             //Create desired roles that does not allready exist
             foreach (var curDesired in desiredRoleAssignments)
             {
-                var sameRoleFromExisting = existingRoleAssignments.Where(ra => ra.properties.principalId == curDesired.PrincipalId && ra.properties.roleDefinitionId.Contains(curDesired.RoleId)).FirstOrDefault();
+                var sameRoleFromExisting = existingRoleAssignmentsForResource.FirstOrDefault(ra => ra.properties.principalId == curDesired.PrincipalId && ra.properties.roleDefinitionId.Contains(curDesired.RoleId));
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Provisioning/Service/RoleProvisioningService.cs:142]: Is there a difference here? Or is it the same, just written different?

File: src/Sepes.RestApi.IntegrationTests/Setup/CustomWebApplicationFactory.cs [hunk 3]
```diff
@@ -107,7 +107,8 @@ protected override void ConfigureWebHost(IWebHostBuilder builder)
                                [ConfigConstants.IS_INTEGRATION_TEST] = "true",
                                ["AllowCorsDomains"] = "http://localhost:80",
                                ["CostAllocationTypeTagName"] = "INTTEST-CostAllocationType",
-                               ["CostAllocationCodeTagName"] = "INTTEST-CostAllocationCode"
+                               ["CostAllocationCodeTagName"] = "INTTEST-CostAllocationCode",
+                               ["DatasetStorageAccountRoleAssignmentId"] = "9145904e-a892-473a-b559-8d87b9858407"
```
Comment (HansKristianVikOlsen) [inline src/Sepes.RestApi.IntegrationTests/Setup/CustomWebApplicationFactory.cs:111]: This is the role id, and I guess this is somewhere to be found in azure? Is it in the manifest there?

**Review by HansKristianVikOlsen — APPROVED** [review]
Looks good! I had some general questions

File: src/Sepes.Provisioning/Service/RoleProvisioningService.cs (hunk 2 above)
Comment (krsteen) [reply src/Sepes.Provisioning/Service/RoleProvisioningService.cs:142]: r is for resource, ra is for roleassignment, it's sort of given from what dbset one is querying. But i agree it might be a bit cryptic for developers who come in at a later state

File: src/Sepes.RestApi.IntegrationTests/Setup/CustomWebApplicationFactory.cs (hunk 3 above)
Comment (krsteen) [reply src/Sepes.RestApi.IntegrationTests/Setup/CustomWebApplicationFactory.cs:111]: This particular one does not exist anywhere, it just a guid i generated i VS. But in live scenarios, the vaue for DatasetStorageAccountRoleAssignmentId will be set in config, and is a custom role found in Azure
