### PR TITLE
fix(vm): vm not getting stuck in updating if previous attempt failed

### LINKED ISSUE #433: Vm Creation: Not updating if previous operation is failed or exceeded max retries
If an update (typicall change VM rule) fails more than MAX_RETRY_COUNT, setting more rules won't re-schedule update.
It just get's stuck in failed mode
Any subsequent operations will have the failing operation as dependent, so the new will never get started
The old one should be cancelled and the new one without dependancy

### PR DESCRIPTION
**Pull request by krsteen**
typically happends when a rule update fails, no new operation is started because it's waiting the
previous one.
closes #433

### CODE REVIEW

File: src/Sepes.Infrastructure/Service/CloudResourceOperation/CloudResourceOperationCreateService.cs [hunk 1]
```diff
@@ -71,18 +55,68 @@ public async Task<CloudResourceOperationDto> CreateUpdateOperationAsync(int sand
...
                 MaxTryCount = CloudResourceConstants.RESOURCE_MAX_TRY_COUNT
             };
 
-
             sandboxResourceFromDb.Operations.Add(newOperation);
             await _db.SaveChangesAsync();
             return await GetOperationDtoInternal(newOperation.Id);
         }
 
+        async Task<CloudResourceOperation> CheckIfOperationsToWaitFor(CloudResource resource, UserDto currentUser)
```
Comment (HansKristianVikOlsen) [inline src/Sepes.Infrastructure/Service/CloudResourceOperation/CloudResourceOperationCreateService.cs]: Did you leave out a word in this function name to make it shorter? Maybe "CheckIfAnyOperationsToWaitFor" would make more sense

**Review by HansKristianVikOlsen — APPROVED** [review]
Looks good! See comment
